### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by KristianFJones** [vanshg/MacAssistant#1]
Does it work for you. I keep getting the error: Error send The operation couldn’t be completed. (gRPC.CallError error 1.). I am attempting to use this because I love google Assistant. And will be following your progress!

**Comment by vanshg** [comment]
Yeah, I get that error too. I've been working to try and figure out what's causing that error, but I'm not sure yet. I'll try and have it resolved soon

**Comment by vanshg** [comment]
Needed updated root certificates. Latest code should no longer have this error

**Comment by KristianFJones** [comment]
Still not working for me

**Comment by vanshg** [comment]
This is still under development. Everything is a WIP

**Comment by KristianFJones** [comment]
It is no longer building for me. I'm getting a EXC_bad_instructions error on Authentor.swift at init

**Comment by KristianFJones** [comment]
Well, I should say no longer running. It does build

**Comment by vanshg** [comment]
You need to create an OAuth client key on Google Console, download the json file, rename it to google_oauth.json and add it to your project

**Comment by KristianFJones** [comment]
Now, It freezes when I try to open the menu. Trying to get the expire date

**Comment by vanshg** [comment]
I have posted a beta release. You can download it at https://github.com/vanshg/MacAssistant/releases
