### ISSUE TITLE
Additional permission settings required in google home app

### ISSUE THREAD

**Issue by pteasima** [vanshg/MacAssistant#11]
Hi, when I ask the assistant anything, it says "Actually, there are some basic settings that need you permission first, just go to the google home app on you phone for more details." I downloaded google home on my iphone but I have no idea what I need to do there. Any ideas?

**Comment by vanshg** [comment]
Hm, I'm not too sure. I would assume you need to go through the set-up process for Google Assistant. Maybe try downloading the Google Assistant app from the App Store and finish any set up in there.

**Comment by pteasima** [comment]
Ah, Google Assistant is not available in my country. Not sure why it sent me to Google Home app, theres no setup process there. Thanks anyway.
