### ISSUE TITLE
"Set a timer for X seconds" doesn't start a timer.

### ISSUE THREAD

**Issue by 7ammer** [vanshg/MacAssistant#12]
Saying "Set a timer for X seconds" doesn't actually seem to start a timer. I assume this could be cause MacAssistant doesn't know what timer app to use?

**Comment by vanshg** [comment]
Unfortunately, I don't think this is something MacAssistant can support at the time. Google doesn't return the intent/result of what you said, so the app doesn't actually know what you want to do. MacAssistant only streams back audio responses from Google, so there's no way to set a timer, and no way to get notified about it. If Google, one day, returns back the intent of the query, I'd be happy to take another look
