### ISSUE TITLE
build Swift compiler error

### ISSUE THREAD

**Issue by mikejrh** [vanshg/MacAssistant#13]
Getting error message with build: /Volumes/HOME/Desktop/MacAssistant-master/MacAssistant/AppDelegate.swift:10:8: Missing required module 'CgRPC'

**Comment by vanshg** [comment]
Have you ran `carthage update` and dragged all the frameworks into the Xcode project?

**Comment by agucova** [comment]
I think it's time to close the issue, as the most probable cause is just missing dependencies.

**Comment by agucova** [comment]
@vanshg
