### ISSUE TITLE
CPU Hog

### ISSUE THREAD

**Issue by purevertigo** [vanshg/MacAssistant#16]
New version just released, takes up all CPU and turns Mac fans on. 

I'm on Sierra if that helps.

thanks

**Comment by vanshg** [comment]
Yep, noticed this issue myself as well. I'm not too sure what causes it since it doesn't happen most of the time. If anyone more experienced with macOS/Swift development could help out or provide some input, that would be greatly appreciated

**Comment by vanshg** [comment]
I'm rewriting the software which should address this concern.
