### ISSUE TITLE
 Skipped building grpc-swift due to the error: Dependency "grpc-swift" has no shared framework schemes

### ISSUE THREAD

**Issue by field210** [vanshg/MacAssistant#17]
I tried to compile on macos using `carthage update --platform macOS`. Here is the log:

> *** Fetching AudioKit
> *** Fetching grpc-swift
> *** Fetching Alamofire
> *** Fetching SwiftyJSON
> *** Fetching KeyHolder
> *** Fetching Magnet
> *** Downloading AudioKit.framework binary at "AudioKit v3.7 Microtonality, Audiobus 3, and new Sample Player"
> *** Checking out swift-protobuf at "0.9.901"
> *** Checking out SwiftyJSON at "3.1.4"
> *** Checking out KeyHolder at "v2.0.1"
> *** Checking out grpc-swift at "b4dc0a0952cd1498d3700ab766b3a35368a594c0"
> *** Checking out Alamofire at "4.4.0"
> *** Checking out Magnet at "v2.0.1"
> *** xcodebuild output can be found in /var/folders/g0/_x3xyh8s43g_g3fz3b409hd40000gn/T/carthage-xcodebuild.oQStCG.log
> *** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
> *** Building scheme "Alamofire macOS" in Alamofire.xcworkspace
> *** Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
> *** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
> *** Skipped building grpc-swift due to the error:
> Dependency "grpc-swift" has no shared framework schemes
> 
> If you believe this to be an error, please file an issue with the maintainers at https://github.com/grpc/grpc-swift/issues/new
> *** Building scheme "Magnet" in Magnet.xcworkspace
> *** Building scheme "KeyHolder" in KeyHolder.xcworkspace
> *** Building scheme "SwiftProtobuf_macOS" in SwiftProtobuf.xcodeproj
> *** Building scheme "SwiftProtobuf_tvOS" in SwiftProtobuf.xcodeproj
> *** Building scheme "SwiftProtobuf_iOS" in SwiftProtobuf.xcodeproj
> *** Building scheme "SwiftProtobuf_watchOS" in SwiftProtobuf.xcodeproj
> *** Building scheme "SwiftyJSON tvOS" in SwiftyJSON.xcworkspace
> *** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
> *** Building scheme "SwiftyJSON watchOS" in SwiftyJSON.xcworkspace
> *** Building scheme "SwiftyJSON OSX" in SwiftyJSON.xcworkspace

**Comment by agucova** [comment]
That is normal and expected, it's not an error.

**Comment by vanshg** [comment]
Yeah. If for some reason, not all dependencies are being built, you can also run just `carthage update`

**Comment by agucova** [comment]
This issue should be closed!

**Comment by agucova** [comment]
@vanshg

**Comment by field210** [comment]
but did not get the output file

**Comment by vanshg** [comment]
@field210 did you try running just `carthage update`?

**Comment by field210** [comment]
`carthage update`
                    

> *** Fetching AudioKit
> *** Fetching grpc-swift
> *** Fetching Alamofire
> *** Fetching SwiftyJSON
> *** Fetching KeyHolder
> *** Fetching Magnet
> *** Checking out KeyHolder at "v2.0.1"
> *** Checking out grpc-swift at "85aff66614d5c1e366e6f4c25241650542448ec8"
> *** Checking out swift-protobuf at "0.9.901"
> *** Checking out Alamofire at "4.4.0"
> *** Checking out Magnet at "v2.0.1"
> *** Downloading AudioKit.framework binary at "AudioKit v3.7 Microtonality, Audiobus 3, and new Sample Player"
> *** Checking out SwiftyJSON at "3.1.4"
> *** xcodebuild output can be found in /var/folders/g0/_x3xyh8s43g_g3fz3b409hd40000gn/T/carthage-xcodebuild.qtl3Mi.log
> *** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
> *** Building scheme "Alamofire macOS" in Alamofire.xcworkspace
> *** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
> *** Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
> *** Skipped building grpc-swift due to the error:
> Dependency "grpc-swift" has no shared framework schemes
> 
> If you believe this to be an error, please file an issue with the maintainers at https://github.com/grpc/grpc-swift/issues/new
> *** Building scheme "Magnet" in Magnet.xcworkspace
> *** Building scheme "KeyHolder" in KeyHolder.xcworkspace
> *** Building scheme "SwiftProtobuf_macOS" in SwiftProtobuf.xcodeproj
> *** Building scheme "SwiftProtobuf_iOS" in SwiftProtobuf.xcodeproj
> *** Building scheme "SwiftProtobuf_tvOS" in SwiftProtobuf.xcodeproj
> *** Building scheme "SwiftProtobuf_watchOS" in SwiftProtobuf.xcodeproj
> *** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
> *** Building scheme "SwiftyJSON OSX" in SwiftyJSON.xcworkspace
> *** Building scheme "SwiftyJSON watchOS" in SwiftyJSON.xcworkspace
> *** Building scheme "SwiftyJSON tvOS" in SwiftyJSON.xcworkspace

**Comment by vanshg** [comment]
@field210 I just uploaded a new Cartfile with an explicit version number. Try pulling that, and see if you get the same issue

**Comment by vanshg** [comment]
I just updated the project to Swift 4/Xcode 9.1. I've also switched from `Carthage` to `CocoaPods`. After pulling the latest changes, open up the new `xcworkspace` file instead of `xcodeproj` and see if it builds then
