### ISSUE TITLE
(Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantClientError error 1.)

### ISSUE THREAD

**Issue by ilteris** [vanshg/MacAssistant#19]
When I try to run it, I get: 
"(Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantClientError error 1.)"

Is there any ideas what could be wrong? Thanks!

**Comment by vanshg** [comment]
Are you using your own OAuth credentials? If not, the error is because I've hit the API limit. The solution is to use your own creds
