### ISSUE TITLE
Conversations are not supported

### ISSUE THREAD

**Issue by rawadhilalgymonji** [vanshg/MacAssistant#2]
It looks like conversations are not supported in MacAssistant. Replying to Google's question starts a new context. Can it be supported?

**Comment by vanshg** [comment]
This is definitely a high priority thing to do. I'll get to it as soon I can!

**Comment by alicoding** [comment]
Any progress on this one? Great plugin btw 👍

**Comment by rac2030** [comment]
I just tested and it seems conversations work.
I tested it against a dialogflow example I made and I could switch into the context of the app and it responded as it does on google home or the assistant simulator

**Comment by vanshg** [comment]
Yes, sorry for the delay in responding. This should be working now with the latest version in development.
