### ISSUE TITLE
Reminders creating doesn't work

### ISSUE THREAD

**Issue by LyashenkoGS** [vanshg/MacAssistant#20]
A phrase "remind me in 45 minutes to get my laundry" - produces a response: "Sorry, create reminders not yet supported".

**Comment by vanshg** [comment]
This is expected behavior. Google doesn't support reminders yet

**Comment by LyashenkoGS** [comment]
So, maybe remove a picture from the project readme to don't confuse users? Android version already supports reminders, checked on a Xiaomi Mi Max.
