### ISSUE TITLE
Cartridge error

### ISSUE THREAD

**Issue by SethuSenthil** [vanshg/MacAssistant#22]
Error: git cannot be built with any available compilers.
Install GNU's GCC
  brew install gcc
I'm getting the error when ever trying to install its dependencies please help!

**Comment by agucova** [comment]
Did you run `brew install gcc`, and if yes, what error did you get?

**Comment by vanshg** [comment]
@SethuSenthil Were you able to fix the issue? By cartridge in your issue title, do you mean Carthage? If so, I've moved the project from Carthage to CocoaPods, so dependency management should be a bit easier now
