### ISSUE TITLE
2 factor verification with the phone using the new method gets stuck

### ISSUE THREAD

**Issue by rac2030** [vanshg/MacAssistant#28]
While login with 2 factor authentication using the new method enabled on the account that only needs a click on yes seems to not work. In the popup it stays at waiting for click on accept and I get the message on my phone and accept it but the accept never reaches MacAssistant.

Without having looked into the code for that part, it seems to me as its not listening to the callback on that action.

Workaround is to click "use other method" on that screen and then click Authenticator and use the old method.

**Comment by vanshg** [comment]
I've noticed this in other applications requiring Google login as well. My hunch is this is a Google issue, and not MacAssistant specific.
