### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by scottrobertson** [vanshg/MacAssistant#30]
Hey

Sorry for the dumb question. I have never done any mac development before, and i am just wondering how to build this project.

I have installed `carthage` and ran `carthage update` which worked fine. However, this does not seem to actually do anything other than clone the dependencies? How do i actually build the `dmg` and/or install?

**Comment by Kluskey** [comment]
Open the xcworkspace and build from there.

I'm now, however, getting the issue of it being written in Swift 3.1 instead of 3.2.

**Comment by vanshg** [comment]
Hey guys, I just updated the project to Swift 4/Xcode 9.1. I've also switched from `Carthage` to `CocoaPods`. After pulling the latest changes, open up the new `xcworkspace` file instead of `xcodeproj` and see if it builds then

**Comment by scottrobertson** [comment]
I am getting the following errors

```
No account for team "DU7NX744DX". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
```

```
No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "DU7NX744DX" with a private key was found.
```

And the following warning:

```

Showing Recent Issues
The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "MacAssistant" target.
```

**Comment by scottrobertson** [comment]
Ok i changed the team to myself, now i get the following error:

```
MacAssistant/AppDelegate.swift:10:8: No such module 'gRPC'
```

**Comment by kuwaitbinary** [comment]
for gRPC issue this will help:

https://medium.com/@siavash_59686/swift-grpc-and-protobuf-integration-68c451c4da1f

**Comment by vanshg** [comment]
@scottrobertson Sorry, this is my bad for not having updated README instructions. In the most recent changes, I added grpc-swift as a submodule, so you're going to have to run `git submodule update`. Once you do that, you're going to have to build the grpc-project as well by cd-ing into `grpc-swift` and running `make`

**Comment by scottrobertson** [comment]
Thanks!

That all worked. One last question... how do i build and export a .app so i can install it? I tried doing an archive, but it does not seem to export a .app. Sorry for all the noob questions :D

**Comment by vanshg** [comment]
If you go to `MacAssistant/build/Debug` there should be a `MacAssistant.app` file. This would be the simplest way to use it for personal use!
