### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by abelland** [vanshg/MacAssistant#31]
I'd would be great if the MacAssistant would work with other languages (Italian, Spanish..)
Any chance to implement this feature?

**Comment by theboylogan** [comment]
I would also like this, since Google support en-GB

I tried to find the code myself but gave up

**Comment by vanshg** [comment]
Google recently released a new version of their Assistant SDK, which supports different languages and locales. Support for this feature will come once I finish upgrading to the new one (in progress right now)
