### ISSUE TITLE
Initial receive error endOfStream The operation couldn’t be completed. 

### ISSUE THREAD

**Issue by drmarvel** [vanshg/MacAssistant#32]
After compiling (master) from source with replaced OAuth credentials, the app asks me to login to my Google account, but after using the hotkey activation method or simply clicking the button I receive:

[2018-01-03 17:09:25.907] API.swift:137 ERROR: Initial receive error endOfStream The operation couldn’t be completed. (MacAssistant.Google_Assistant_Embedded_V1Alpha2_EmbeddedAssistantClientError error 1.)
[2018-01-03 17:09:50.141] API.swift:99 INFO: Closed send

**Comment by ernestp** [comment]
Have same error

**Comment by vanshg** [comment]
I started getting this error as well when I tried upgrading to the latest Assistant SDK version. I'll try and get it fixed soon

**Comment by dlh3** [comment]
I experienced this while trying to build, and now I can't even run the 0.2 Beta which I had previously downloaded.  When I try to run it, it opens briefly, but exits almost immediately.  I suppose it is crashing.

Any way to get the beta version running again?

**Comment by vanshg** [comment]
Hm, not too sure what that error is. I will be trying to fix the endOfStream error this weekend hopefully

**Comment by BunFluffpaws** [comment]
Same error, from the same situation it seems. (after compiling)
Does anything need to be updated in the system to allow the app to listen, because i do not get a waveform, and it would seem the error is coming from google because they are not receiving any audio so they end it. A api error for this does show up in the google console which is why i believe its a audio problem.

Running osx 10.13.2 if that helps?

Also Thanks for your work on this, it would be awesome to have this on osx as i use it on android quite a lot.

**Comment by vanshg** [comment]
@BunFluffpaws Nothing needs to be updated, it's just that I broke the app when I tried to upgrade to the newest Assistant SDK version. I really should have done it on a separate branch. In the meantime, if you'd like to try and get it to work, you can try downloading a version from the releases page or checking out an older commit.

**Comment by vanshg** [comment]
I've also spent many hours trying to find the cause of this bug and why it's not working anymore to not much avail. Google doesn't provide descriptive error messages which makes it extremely hard to narrow down the root cause of the issue. Any help would be greatly appreciated.

**Comment by gleitz** [comment]
I checked out `c31049d` and was able to avoid the error.

**Comment by vanshg** [comment]
I'm working on an updated version of the software, and I'm pretty sure I've identified the source of the error. I was making calls to the API in the wrong order which was throwing things off. Stay tuned.
