### ISSUE TITLE
Attaching screenshots to Build Instructions

### ISSUE THREAD

**Issue by navanchauhan** [vanshg/MacAssistant#35]
# Enhancement
I think we should attach some images to build instructions, I could do that if it's fine?

**Comment by vanshg** [comment]
Sure, that'd be great if you could do that!

**Comment by navanchauhan** [comment]
Check my repo [MacAssistant](https://github.com/navanchauhan/MacAssistant) If it's fine I'll open a pull request and also I've made a short video on getting the json file which I've directly linked to the README.md
