### ISSUE TITLE
Support text input 

### ISSUE THREAD

**Issue by oriharel** [vanshg/MacAssistant#4]
Sometimes I'm not able to speak out loud, but I would like to access the assistant via text. #

**Comment by vanshg** [comment]
I would love to be able to do that too, but unfortunately the Google Assistant API doesn't support such a thing. 

It may be possible to achieve something like this by using a TTS engine and converting typed text into audio, and then transferring that audio to Google, but it's a hacky workaround that I may or may not ever get to

**Comment by oriharel** [comment]
I'll see what I can do to help.

**Comment by jubby2000** [comment]
@oriharel @vanshg 
"there’s now support for text-based queries and responses"
https://www.theverge.com/circuitbreaker/2017/12/20/16802554/google-assistant-sdk-update-new-languages-configuration-settings-actions

**Comment by patkoscsaba** [comment]
... And here is the official announcement on Google: 
https://developers.googleblog.com/2017/12/the-google-assistant-sdk-new-languages.html

**Comment by vanshg** [comment]
Awesome! I'll definitely try to get this implemented ASAP

**Comment by vanshg** [comment]
Let's keep this open until it's implemented

**Comment by vanshg** [comment]
This is coming soon with an upgrade to the newest Assistant SDK version.
