### ISSUE TITLE
Index_pack

### ISSUE THREAD

**Issue by OctoPenguin** [vanshg/MacAssistant#41]
I attempted to build MacAssistant using the instructions outlined in the readme. Unfortunately, when I tried to `git clone` the repository using `--recursive`, I got the following output:

`Cloning into 'MacAssistant'...
remote: Counting objects: 1068, done.
remote: Total 1068 (delta 0), reused 0 (delta 0), pack-reused 1067
Receiving objects: 100% (1068/1068), 13.10 MiB | 39.00 KiB/s, done.
fatal: unable to open /Users/sam/Program Files/MacAssistant/.git/objects/pack/tmp_pack_xkqMkb: No such file or directory
fatal: index-pack failed`

**Comment by vanshg** [comment]
I believe this is a problem with your git CLI or environment. It should be unrelated to this project.
