### ISSUE TITLE
Mac assistant not building

### ISSUE THREAD

**Issue by dynomite567** [vanshg/MacAssistant#42]
I keep on having this problem when trying to build, can this be fixed?
![screen shot 2018-02-13 at 1 18 37 pm](https://user-images.githubusercontent.com/17055345/36174456-37fb3efa-10c1-11e8-8afc-b78a4b27800c.png)

**Comment by Bauke777** [comment]
This worked for me:
- Don't do conversion to Swift 4
- Add `google_oauth.json` and `google_oauth_dev.json` files to the MacAssistant/MacAssistant/ directory.

**Comment by dynomite567** [comment]
Ok, its been a while, but how do I tell Xcode to not convert to swift 4? I cant seem to figure that out.

**Comment by imrichvalach** [comment]
AudioKit 4.2 was just released and xcode 9.3 compiles MacAssistant successfully after updating AudioKit.

Steps:
1. Close Xcode
2. `cd` to MacAssistant directory
3. run `pod update 'AudioKit'; optionally use `--verbose` for progress

**Comment by Patrik-svobodik** [comment]
<img width="250" alt="snimek obrazovky 2018-04-14 v 20 25 47" src="https://user-images.githubusercontent.com/25883885/38771362-290e7aca-4022-11e8-8855-389234d2b7b2.png">
what should I do with this?

**Comment by imrichvalach** [comment]
When `try`ing to start or stop AudioKit, an error can occur. In code, this error is not caught and if this error would indeed occur, there is no way for the user to know. Xcode highlights this as a point for improvement.

For fixing, try [google](http://lmgtfy.com/?q=call+can+throw+but+error+is+not+handled+xcode) or [this StackOverflow answer](https://stackoverflow.com/questions/45024229/ios-call-can-throw-but-is-not-marked-with-try-and-the-error-is-not-handled?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

If you do not care about catching errors and just want to hack it, append `!` after `try` in lines 115 and 128. e.g.: `try! AudioKit.stop()`. this should remove the warnings.

**Comment by Patrik-svobodik** [comment]
Oh thanks, this helped me a lot. I just wanted to somehow compile it.

**Comment by Patrik-svobodik** [comment]
Now I have to find out how to get google_oauth_dev.json

**Comment by Patrik-svobodik** [comment]
I am really not good at programming and compiling, is there somebody who would compile it for me is I provide you my google_oauth.json? Please contact me @ svob.pata@gmail.com (please don't spam me with some crap)

**Comment by vanshg** [comment]
I have an updated version of the software in the works, and I'll be sure to have an option from the GUI to use your own google_oauth.json. Stay tuned. It should also be simpler to build.
