### ISSUE TITLE
AudioKit.start(), AudioKit.stop(): Call can throw, but it is not marked with 'try' and the error is not handled

### ISSUE THREAD

**Issue by imrichvalach** [vanshg/MacAssistant#45]
`Error: Call can throw, but it is not marked with 'try' and the error is not handled` appears in AssistantViewController.swift on lines `115` and `128` in functions `startListening()` and `stopListening()`, respectively.

The error showed after updating to AudioKit 4.2. However, this might not be the cause, as previously I could not compile AudioKit, since it did not support Swift 4.1.

**Comment by vanshg** [comment]
I'm working on a revamped version of this software and this should be fixed. Stay tuned.
