### ISSUE TITLE
possibility to use keyboard

### ISSUE THREAD

**Issue by jordyvandomselaar** [vanshg/MacAssistant#49]
When at work it'd be weird if I started talking to my laptop. It'd be awesome if I could type my queries to the assistant, like you can on the phone.

**Comment by andrewdavidmackenzie** [comment]
I had the same thought and considered looking into it. 

As in some situations you don't want to speak or have others hear some queries.

The ideal would be a small text box on the dialog that opens from the Mac menu or via keyboard shortcut.

**Comment by Stvad** [comment]
Came here searching for this :) It'd be great! As a follow-up - integration with Alfred can be considered.

**Comment by jubby2000** [comment]
Duplicate of #4

**Comment by vanshg** [comment]
This should be working now!
