### ISSUE TITLE
Compound Ticket

### ISSUE THREAD

**Issue by praging** [vanshg/MacAssistant#58]
I'm not exactly sure how this is supposed to work, but as of now I am only able to type -- clicking on the microphone is disabled, I am unable to access any kind of settings menu and I am unable to quit without going to Activity Monitor.

**Comment by praging** [comment]
Additionally, every time I click on the assistant (hotkey does not work) it opens another window.

**Comment by vanshg** [comment]
Yeah, I really should have a separate development branch. In current master branch there's definitely bugs and you're right, it's incomplete.

**Comment by vanshg** [comment]
Duplicate window is fixed. Mic functionality added. To quit for right now, you can click on the window and hit Command-Q, until I add a better way. Adding a Preferences is a high priority and I will address it soon.
