### ISSUE TITLE
MacAssistant not responding after speaking (Hitting API limit/quota)

### ISSUE THREAD

**Issue by 7ammer** [vanshg/MacAssistant#6]
This application looks great! :)
Unfortunately after speaking it doesn't respond with anything. The application hasn't frozen it just doesn't do anything.

I'm not sure what error logs to give you so let me know and I'll send them your way if you're interested.

**Comment by vanshg** [comment]
Does the UI update with the text you've spoken? And does relaunching the app seem to fix the problem? I'm aware of a bug right now where the authentication token expires and doesn't get refreshed until relaunch, which might be causing the issue you're having

**Comment by nullhart** [comment]
I know google recently updated their python sample and it changed quite a bit. This might be related to why it is no longer working.

Love the idea... keep up the good work!

**Comment by jakecross** [comment]
Hi there - experiencing same problem on macOS 10.12.4 on a Mid-2012 13" MacBook Air.  App appears to be listening (status bar changes color and shows waveform when speaking) but does not display the spoken text or act on it at all.

**Comment by jasongoldsmith** [comment]
Same issue here. 

Steps to reproduce

1) Launch the app
2) double tap the left command key
3) The MacAssist dialog will open and play a sound to indicate it is listening
4) Ask "What is the capital of California?" - the wave form will appear and indicate the speech is being heard by Mac Assist
5) The waveform will then go flat indicating there is no additional sound.
6) Ask "What's 10 + 10?" the waveform will appear again and then return to flat.

**Comment by jasongoldsmith** [comment]
Deleted the application and reinstalled it and now it works.

**Comment by 7ammer** [comment]
I just restarted my laptop and it's now working.

**Comment by malonehedges** [comment]
Have this issue too. Tried deleting and reinstalling with no success.

**Comment by vanshg** [comment]
Hey guys! It turns out I've hit the quota for the Assistant API limit. I'm working with Google right now to resolve this! Hopefully I can have it fixed soon

**Comment by vanshg** [comment]
On a related note, I will work on incorporating a better way to handle and present such errors in the application

**Comment by malonehedges** [comment]
@vanshg Well congratulations 😛 I'll try to set it up with my own credentials in the meantime.

**Comment by codeOfRobin** [comment]
@vanshg wouldn't it be a better idea to let users input credentials on their own rather than require them to build and run by themselves?

**Comment by Wowfunhappy** [comment]
Would love a way to put in my own api key without recompiling the app. :)

**Comment by navanchauhan** [comment]
This bug is happening even with my json file
