### ISSUE TITLE
MacAssistant not moveable and/or should show/hide

### ISSUE THREAD

**Issue by seagullmouse** [vanshg/MacAssistant#66]
Once I've launched Mac Assistant the bubble just sits there on my desktop all the time when I am not interacting with it. The bubble cannot be moved/dragged around to another place on the desktop.

I think **one** of the below enhancements would greatly aid usability.
- Enhancement 1: Make the bubble moveable.
- Enhancement 2: Make the bubble start to record as soon as it opens (see #43) **and** close after recording.

**Comment by vanshg** [comment]
I'm working on adding a Preferences window right now and this is in there. If you take a look at the current commits and manually show preferences you might be able to enable it (but YMMV because both the Preferences window and the Prefenrce itself are still WIP)

**Comment by vanshg** [comment]
I'll close this once I commit this in a working state
