### ISSUE TITLE
Next Update Release

### ISSUE THREAD

**Issue by bkjimena11** [vanshg/MacAssistant#67]
When will the next update get released?

**Comment by vanshg** [comment]
Probably soon -- I just graduated and should have a little bit more free time to work on this now.

**Comment by bkjimena11** [comment]
Oh OK. Cool. How soon do you think will you be able to release an update? And will we be able to visual see what Google Assistant replies back when we ask it something?

**Comment by vanshg** [comment]
I am aiming for February. I completely revamped the project in the interest of making it feel like a more polished product. There are still some issues to be sorted out. However, if you build from source, you can use MacAssistant in a somewhat working state. And yes, you can already visually see what Google Assistant replies when you ask it something!

**Comment by bkjimena11** [comment]
I don't see what Google Assistant says when I ask it something.

**Comment by bkjimena11** [comment]
I don't see what Google Assistant says when I ask it something.

**Comment by vanshg** [comment]
Are you building from source? Only that has it. The builds on the downloads page do not.

**Comment by vanshg** [comment]
There is no download available right now. You have to build from source

**Comment by bkjimena11** [comment]
How do I do that if I don't know how to program?

**Comment by bkjimena11** [comment]
How do I do that if I don't know how to program?

**Comment by vanshg** [comment]
There's instructions in the README. No explicit programming required to get it working, just some setup.

**Comment by bkjimena11** [comment]
Where is the README?

**Comment by vanshg** [comment]
https://github.com/vanshg/MacAssistant/blob/master/README.md#build-instructions

**Comment by bkjimena11** [comment]
Where is the location of "./MacAssistant/Config/google_oauth.json" on my computer?

**Comment by vanshg** [comment]
The "." refers to wherever you downloaded the repo to

**Comment by bkjimena11** [comment]
So I can create a folder called Config since it doesn't exist yet?

**Comment by bkjimena11** [comment]
When I open the contents for MacAssistant, I have a folder called Contents. Then inside that folder, I have folders called _Code Signature, Frameworks, MacOS & Resources. Also in that folder are files called Info.plist & PkgInfo.

**Comment by bkjimena11** [comment]
What is happening now?

**Comment by bkjimena11** [comment]
Can you help me, please?

**Comment by vanshg** [comment]
Git clone the repository, follow the directions in the README to get the Google OAuth credentials, and follow the build instructions in the README

**Comment by bkjimena11** [comment]
I already got the Google OAuth credentials, how do I git clone the repository?

**Comment by domenicoblanco** [comment]
You have to install [brew for macOS](https://brew.sh) and then you could insert this command in your terminal `git clone https://github.com/vanshg/MacAssistant.git`

**Comment by bkjimena11** [comment]
I have installed brew and put in the command git clone https://github.com/vanshg/MacAssistant.git in the terminal, what is the next step?

**Comment by domenicoblanco** [comment]
You have to open the Finder and go to your users folder, open MacAssistant folder and open again MacAssistant folder, at this point, you should see a folder called Config, copy here your oauth token and change the name to google_oauth

**Comment by bkjimena11** [comment]
I do not see a folder called Config. I downloaded the 0.2 Soure.zip file. Is that right?
<img width="1015" alt="screen shot 2018-12-20 at 8 16 42 am" src="https://user-images.githubusercontent.com/45953458/50287204-e399eb00-042f-11e9-92e8-7ecb90eb29d3.png">

**Comment by domenicoblanco** [comment]
You should delete the zip and use the version downloaded from Git, the default folder is `/Users/YourUsername/MacAssistant`

**Comment by bkjimena11** [comment]
How do I run the program now?

**Comment by domenicoblanco** [comment]
In order to run the program, you have to download xCode from the Mac App Store and run it once (to download some components) and then you have to navigate again inside the same folder in which there is the Config folder (`/Users/YourUsername/MacAssistant`) and open `MacAssistant.xcworkspace`. Once xCode loaded the project you can simply press the play button.
To convert the project to a .app program, you have to go under **Product → Archive** and archive the app.

**Comment by bkjimena11** [comment]
Is there a way to check for updates automatically?

**Comment by domenicoblanco** [comment]
Not atm, this is a pre-release version. I suggest you to come and check. I've this repository on my favorites and check it at least twice a week.

**Comment by bkjimena11** [comment]
Is an archive called BoringSSL supposed to be made?

**Comment by domenicoblanco** [comment]
If I'm not wrong, it's one of the dependecies of this project so, it's normal

**Comment by bkjimena11** [comment]
<img width="1112" alt="screen shot 2018-12-21 at 11 14 31 pm" src="https://user-images.githubusercontent.com/45953458/50370521-4b5a4e00-0576-11e9-9aaa-17aa1bb79e2a.png">

This is what I am stuck on now, what do I need to do?

**Comment by domenicoblanco** [comment]
You're trying to export a dependency. You have to come back to xCode, select MacAssistant and archive it. Next you have to click Distribute Content into a local app

**Comment by bkjimena11** [comment]
Is it the first MacAssistant folder that I archive or the other folder named "MacAssistant " inside the first folder?

**Comment by vanshg** [comment]
Are you able to run it at all from Xcode (You can run it by hitting Command-R)

**Comment by bkjimena11** [comment]
What do you mean vanshg?

**Comment by bkjimena11** [comment]
Which file do I need to open in Xcode?

**Comment by bkjimena11** [comment]
When I open MacAssistant.xcworkspace, I press the play button. Then after that I press the archive option under product, then this is when the boringssl thing that I mentioned in other messages appears. I really don't understand what I should be doing. Can someone give a step by step guide on how I should be doing this?

**Comment by domenicoblanco** [comment]
When you run It, It works?

**Comment by bkjimena11** [comment]
It does 133 tasks when I press the play button, is that right?

**Comment by domenicoblanco** [comment]
I'm not sure about the number of tasks but it should be right. What I mean is if you're able to use MacAssistant running it from the play button

**Comment by bkjimena11** [comment]
No.

**Comment by domenicoblanco** [comment]
In this case, there's an error during the building of the project. Are you able to see any error?

**Comment by bkjimena11** [comment]
I will show you what happens.

**Comment by bkjimena11** [comment]
It works now.
