### ISSUE TITLE
Not showing data structures

### ISSUE THREAD

**Issue by domenicoblanco** [vanshg/MacAssistant#68]
Hi, I'm using the version compiled from source and there's only support for text responses. Could be possible to add other data structures compatible with Google Assistant such as Carousel, Cards and others? There's also a bug that truncates the phrase (but the text is stil present and I'm able to copy it to the clipboard), could you split it in lines (about 50 characters per line)?

**Comment by vanshg** [comment]
Unfortunately, Google doesn't explicitly expose that in their gRPC API/Assistant SDK. There is a visual response that can be used (but I won't have control over how it is displayed). I am planning on adding support for that.
