### ISSUE TITLE
AudioKit problems

### ISSUE THREAD

**Issue by Migelo** [vanshg/MacAssistant#90]
MacOS: 10.15.7
Xcode:  12.3 (12C33)

I cloned the repo, switched to the SwiftPM branch (44e33ab5ffb6d7e6ec717b4353e77d40b5be73cd) and tried to build the app when I got this error.

In `AudioEngine.swift` I get this error:
```
AudioKit: Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.3.2 compiler: /Users/username/MacAssistant/MacAssistant/AudioKit.framework/Modules/AudioKit.swiftmodule/x86_64-apple-macos.swiftmodule
```

On the master branch I got the same error but after upgrading AudioKit to [4.9.4](https://github.com/AudioKit/AudioKit/releases/tag/v4.9.4), because that is the version which turned on the library evolution feature, I get 2k+ errors.

<img width="910" alt="image" src="https://user-images.githubusercontent.com/6537512/105513291-6ad28080-5cd2-11eb-8e70-a0c09d15781b.png">

It seems some changes in AudioKit from version [4.6.4](https://github.com/AudioKit/AudioKit/releases/tag/v4.6.4) to [4.9.4](https://github.com/AudioKit/AudioKit/releases/tag/v4.9.4) are breaking this project somehow. 

<img width="908" alt="image" src="https://user-images.githubusercontent.com/6537512/105513945-3ad7ad00-5cd3-11eb-84c7-be255b8288f3.png">

@vanshg could you please point me in some direction on how to solve this issue? Or should I ask the AudioKit ppl for help? I am very eager to solve this issue, but I definitely need some guidance.

Thank you for your time.

**Comment by vanshg** [comment]
Hi @Migelo, that branch isn't stable yet, so there's no guarantee it should've been working to begin with. If you can resolve it, I'm more than happy to accept Pull Requests 🙂
